name: Semantic Pull Requests

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  semantic:
    name: Semantic Pull Requests
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
